// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLIwPNZ_1w3UHDSbE4Cnr2z9lzzbEOMY',
    appId: '1:686507061891:web:f571c1c41d0a10d3ace1b6',
    messagingSenderId: '686507061891',
    projectId: 'fiksopp-bb927',
    authDomain: 'fiksopp-bb927.firebaseapp.com',
    storageBucket: 'fiksopp-bb927.firebasestorage.app',
    measurementId: 'G-7BH15CVTME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqYLhVraIKfe8jBdT0DDTGrIydnbmQVY',
    appId: '1:686507061891:android:9627fbe8d91ed069ace1b6',
    messagingSenderId: '686507061891',
    projectId: 'fiksopp-bb927',
    storageBucket: 'fiksopp-bb927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLpJJQ35VE8O8gNd9hC8IxYnzqXeYAwMk',
    appId: '1:686507061891:ios:e5532bd27c71ce2cace1b6',
    messagingSenderId: '686507061891',
    projectId: 'fiksopp-bb927',
    storageBucket: 'fiksopp-bb927.firebasestorage.app',
    androidClientId: '686507061891-2700lpdphhm8ggbbsmj9gs99q89mf1ir.apps.googleusercontent.com',
    iosClientId: '686507061891-ns1f9delln3tg7g54d4nu7p3jbbuk3mr.apps.googleusercontent.com',
    iosBundleId: 'fiksopp.inoor.buzz.provider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLpJJQ35VE8O8gNd9hC8IxYnzqXeYAwMk',
    appId: '1:686507061891:ios:f28f9d4d6d182300ace1b6',
    messagingSenderId: '686507061891',
    projectId: 'fiksopp-bb927',
    storageBucket: 'fiksopp-bb927.firebasestorage.app',
    androidClientId: '686507061891-2700lpdphhm8ggbbsmj9gs99q89mf1ir.apps.googleusercontent.com',
    iosClientId: '686507061891-4akb19hpda4tr82eh66u96snlifeh8et.apps.googleusercontent.com',
    iosBundleId: 'fiksopp.inoor.handymanProviderFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdLIwPNZ_1w3UHDSbE4Cnr2z9lzzbEOMY',
    appId: '1:686507061891:web:eb6df65a9bc2d5b2ace1b6',
    messagingSenderId: '686507061891',
    projectId: 'fiksopp-bb927',
    authDomain: 'fiksopp-bb927.firebaseapp.com',
    storageBucket: 'fiksopp-bb927.firebasestorage.app',
    measurementId: 'G-Y68DMYRY2D',
  );
}
